%YAML 1.2
---
global:
    database_file_path: 'database'
    database_file_name: 'system.db'
    #参数log_level可选项
    #CRITICAL = 50
    #FATAL = CRITICAL
    #ERROR = 40
    #WARNING = 30
    #WARN = WARNING
    #INFO = 20
    #DEBUG = 10
    log_level: 10
    log_file_path: './logs/main.log'

influxDB:
    host: 'localhost'
    port: '8086'
    #path当为Windows平台时才会生效,指明可执行文件存在路径
    path: './Env/influxdb'

uvicorn:
    host: '0.0.0.0'
    port: 8004